services:
  json-server:
    build:
      context: .
      network: host
    image: json-server
    container_name: json-server
    volumes: 
      - ./db.json:/app/db.json
    ports:
      - "80:3000"
